version: '2'
services:
    accountoperation-mariadb:
        container_name: accountoperation-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/accountoperation/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=accountoperation
        ports:
            - 3306:3306
