version: '2'
services:
    account-mariadb:
        container_name: account-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/account/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=account
        ports:
            - 3306:3306
